const texts = {
    'original(english)': `Look at this lead pencil. There's not a single person in the world who could make this pencil. Remarkable statement? Not at all. The wood from which it is made, for all I know, comes from a tree that was cut down in the state of Washington. To cut down that tree, it took a saw. To make the saw, it took steel. To make steel, it took iron ore. This black center—we call it lead but it's really graphite, compressed graphite—I'm not sure where it comes from, but I think it comes from some mines in South America. This red top up here, this eraser, a bit of rubber, probably comes from Malaya, where the rubber tree isn't even native! It was imported from South America by some businessmen with the help of the British government. This brass ferrule? [Self-effacing laughter.] I haven't the slightest idea where it came from. Or the yellow paint! Or the paint that made the black lines. Or the glue that holds it together. Literally thousands of people co-operated to make this pencil. People who don't speak the same language, who practice different religions, who might hate one another if they ever met! When you go down to the store and buy this pencil, you are in effect trading a few minutes of your time for a few seconds of the time of all those thousands of people. What brought them together and induced them to cooperate to make this pencil? There was no commissar sending ... out orders from some central office. It was the magic of the price system: the impersonal operation of prices that brought them together and got them to cooperate, to make this pencil, so you could have it for a trifling sum. That is why the operation of the free market is so essential. Not only to promote productive efficiency, but even more to foster harmony and peace among the peoples of the world.`,
    'spanish': `Mira este lápiz de plomo. No hay una sola persona en el mundo que pueda hacer este lápiz. ¿Declaración notable? De ningún modo. La madera de la cual está hecha, por lo que sé, proviene de un árbol que fue cortado en el estado de Washington. Para cortar ese árbol, tomó una sierra. Para hacer la sierra, tomó acero. Para hacer acero, tomó mineral de hierro. Este centro negro, lo llamamos plomo, pero en realidad es grafito, grafito comprimido, no estoy seguro de dónde viene, pero creo que proviene de algunas minas en Sudamérica. Este top rojo aquí, este borrador, un poco de goma, probablemente proviene de Malaya, ¡donde el árbol de caucho ni siquiera es nativo! Fue importado de Sudamérica por algunos empresarios con la ayuda del gobierno británico. Esta virola de latón? [Risa burlona.] No tengo la menor idea de dónde vino. O la pintura amarilla! O la pintura que formaban las líneas negras. O el pegamento que lo mantiene unido. Literalmente miles de personas cooperaron para hacer este lápiz. Personas que no hablan el mismo idioma, que practican diferentes religiones, que pueden odiarse unos a otros si alguna vez se conocen. Cuando vas a la tienda y compras este lápiz, estás en efecto intercambiando algunos minutos de tu tiempo por unos pocos segundos del tiempo de todos esos miles de personas. ¿Qué los unió y los indujo a cooperar para hacer este lápiz? No había comisario enviando ... órdenes de alguna oficina central. Fue la magia del sistema de precios: la operación impersonal de los precios los unió y los hizo cooperar para hacer este lápiz, por lo que podría tenerlo por una suma insignificante. Por eso es tan esencial el funcionamiento del libre mercado. No solo para promover la eficiencia productiva, sino más aún para fomentar la armonía y la paz entre los pueblos del mundo.`,
    'german': `Schau dir diesen Bleistift an. Es gibt keinen Menschen auf der Welt, der diesen Stift herstellen kann. Bemerkenswerte Aussage? Auf keinen Fall Das Holz, aus dem es hergestellt wird, stammt meines Wissens aus einem Baum, der im Bundesstaat Washington gefällt wurde. Um diesen Baum zu fällen, nahm er eine Säge. Um die Säge herzustellen, nahm er Stahl. Um Stahl herzustellen, nahm er Eisenerz. Dieses schwarze Zentrum nennen wir Lead, aber es ist wirklich Graphit, komprimierter Graphit. Ich bin nicht sicher, woher es kommt, aber ich denke, es kommt aus einigen Minen in Südamerika. Dieses rote Top, dieser Radiergummi, ein bisschen Gummi, stammt wahrscheinlich aus Malaya, wo der Gummibaum nicht einmal heimisch ist! Es wurde von einigen Geschäftsleuten mit Hilfe der britischen Regierung aus Südamerika importiert. Diese Messingzwinge? [Spottendes Lachen.] Ich habe keine Ahnung, woher er kam. Oder die gelbe Farbe! Oder die Farbe, die die schwarzen Linien bildete. Oder der Klebstoff, der es zusammenhält. Buchstäblich arbeiteten tausende von Menschen an diesem Stift. Menschen, die nicht dieselbe Sprache sprechen, verschiedene Religionen ausüben, die sich hassen können, wenn sie sich jemals treffen. Wenn Sie in den Laden gehen und diesen Stift kaufen, tauschen Sie tatsächlich einige Minuten Ihrer Zeit für Tausende von Menschen aus. Was hat sie vereint und sie dazu gebracht, an diesem Stift mitzuarbeiten? Es gab keinen Kommissar, der Bestellungen von einer zentralen Stelle aus sandte. Es war die Magie des Preissystems: Die unpersönliche Funktionsweise der Preise vereinte sie und brachte sie dazu, diesen Bleistift zusammenzubringen, sodass ich ihn für eine unbedeutende Summe erhalten konnte. Deshalb ist das Funktionieren des freien Marktes so wichtig. Nicht nur zur Förderung der Produktivität, sondern noch mehr zur Förderung der Harmonie und des Friedens zwischen den Völkern der Welt.`,
    'french': `Regarde ce crayon. Personne au monde ne peut fabriquer ce stylo. Déclaration notable? À ma connaissance, le bois n\'est pas issu d\'un arbre abattu dans l\'État de Washington. Pour couper cet arbre, il a pris une scie. Pour fabriquer la scie, il a pris de l\'acier. Pour fabriquer de l\'acier, il a pris du minerai de fer. Nous appelons ce fil noir au centre, mais il s'agit vraiment de graphite, de graphite comprimé. Je ne sais pas d\'où ça vient, mais je pense que ça vient de quelques mines d\'Amérique du Sud. Ce sommet rouge, cette gomme, un peu de caoutchouc, vient probablement de Malaisie, où l'hévéa n'est même pas originaire! Il a été importé d\'Amérique du Sud par des hommes d\'affaires avec l\'aide du gouvernement britannique. Cette virole en laiton? [Rires moqueurs.] Je ne sais pas d\'où il venait. Ou la couleur jaune! Ou la couleur qui compose les lignes noires. Ou la colle qui le tient ensemble. Des milliers de personnes ont littéralement travaillé sur ce stylo. Les personnes qui ne parlent pas la même langue ont des religions différentes qui peuvent se détester si elles se rencontraient un jour. Lorsque vous allez au magasin pour acheter ce stylo, vous passez quelques minutes de votre temps avec des milliers de personnes. Qu\'est-ce qui les a réunis et les a amenés à travailler sur ce stylo? Il n\'y avait pas de commissaire qui a envoyé des commandes à partir d\'un emplacement central. C\'était la magie du système de prix: la nature impersonnelle des prix les unissait et les obligeait à réunir ce crayon afin que je puisse l\'obtenir pour une somme modique. C\'est pourquoi le fonctionnement du marché libre est si important. Non seulement pour promouvoir la productivité, mais encore plus pour promouvoir l\'harmonie et la paix entre les peuples du monde.`,
    'english again': `Look at this pencil. No one in the world can make this pen. Notable statement? To my knowledge, the wood is not from a fallen tree in Washington State. To cut this tree, he took a saw. To make the saw, he took steel. To make steel, he took iron ore. We call this black wire in the center, but it\'s really graphite, compressed graphite. I do not know where it comes from, but I think it comes from some mines in South America. This red top, this rubber, a little rubber, probably comes from Malaysia, where rubber is not even native! It was imported from South America by businessmen with the help of the British government. This brass ferrule? [Laughter] I do not know where he came from. Or the yellow color! Or the color that makes up the black lines. Or the glue that holds it together. Thousands of people literally worked on this pen. People who do not speak the same language have different religions that can hate each other if they meet one day. When you go to the store to buy this pen, you spend a few minutes of your time with thousands of people. What brought them together and led them to work on this pen? There was no commissioner who sent orders from a central location. It was the magic of the price system: the impersonal nature of the prices united them and compelled them to collect this pencil so that I could obtain it for a small fee. This is why the operation of the free market is so important. Not only to promote productivity, but even more to promote harmony and peace among the peoples of the world.`
};


function disaplayTexts(texts) {
    const template = document.querySelector('#translations .template-hidden');
    const article = document.querySelector('#translations');
    const popupText = document.querySelector('#animatedModal .popup-text');
    const popupLanguage = document.querySelector('#animatedModal .popup-language');

    Object.keys(texts).forEach(addText);

    addText('original(english)');

    function addText(language) {
        const text = texts[language]
        const element = template.cloneNode(true);
        const textDiv = element.querySelector('.text');
        const languageDiv = element.querySelector('.language');
        $(element).animatedModal({
            animatedIn: 'fadeInUp',
            color: 'white',
            animatedOut: 'fadeOutDown',
        });

        textDiv.innerHTML = text;
        languageDiv.innerHTML = language;

        element.addEventListener('click', function () {
            popupText.innerHTML = text;
            popupLanguage.innerHTML = language;
        });
        element.classList.remove('template-hidden');
        article.appendChild(element)
    }
}


disaplayTexts(texts);